# Generated by Django 4.1.1 on 2022-09-10 15:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('branch', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=14, null=True)),
                ('CG', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField(default=1)),
                ('enrollment_number', models.CharField(blank=True, max_length=8, null=True)),
                ('candidate_from', models.CharField(choices=[('P', 'Project'), ('T', 'Test'), ('O', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Interview_Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=200)),
                ('custom_questions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('I', 'Interview'), ('P', 'Project'), ('T', 'Test')], max_length=1)),
                ('dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('session', models.IntegerField(default=2022)),
                ('season_type', models.CharField(choices=[('designer', 'Designer'), ('developer', 'Developer')], max_length=10)),
                ('is_ongoing', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.IntegerField(blank=True, null=True)),
                ('Weightage', models.IntegerField(blank=True, default=1)),
                ('name', models.CharField(max_length=200)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.round')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('role', models.CharField(choices=[('designer', 'Designer'), ('developer', 'Developer')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Sectional_Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Round_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('marks_obtained', models.IntegerField(blank=True, default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.interview_panel')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.round')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.candidate')),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.season'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('submission_link', models.URLField(blank=True, max_length=300, null=True)),
                ('asignee', models.ManyToManyField(to='mainapp.user')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.section')),
            ],
        ),
        migrations.AddField(
            model_name='interview_panel',
            name='members',
            field=models.ManyToManyField(to='mainapp.user'),
        ),
        migrations.AddField(
            model_name='interview_panel',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.season'),
        ),
        migrations.CreateModel(
            name='InfoToConvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=500)),
                ('is_exterminated', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_conveyed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.candidate')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='rounds',
            field=models.ManyToManyField(through='mainapp.Round_Info', to='mainapp.round'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.season'),
        ),
    ]
