# Generated by Django 4.1.1 on 2022-09-24 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='Weightage',
            new_name='weightage',
        ),
    ]
