# Generated by Django 4.1.1 on 2022-09-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_round_info_panel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infotoconvey',
            name='is_exterminated',
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_exterminated',
            field=models.BooleanField(default=False),
        ),
    ]
