# Generated by Django 4.1.1 on 2022-09-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_weightage_section_weightage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_status',
            name='marks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question_status',
            name='normalized_marks',
            field=models.FloatField(default=models.IntegerField(blank=True, default=0, null=True)),
        ),
    ]
