# Generated by Django 4.1.1 on 2022-09-10 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_infotoconvey_is_exterminated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('normalized_marks', models.FloatField(default=models.IntegerField(blank=True, null=True))),
                ('is_checked', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.candidate')),
            ],
        ),
    ]
