# Generated by Django 4.1.1 on 2022-09-11 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_question_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name_plural': 'Candidates'},
        ),
        migrations.AlterModelOptions(
            name='infotoconvey',
            options={'verbose_name_plural': 'InfoToConvey'},
        ),
        migrations.AlterModelOptions(
            name='interview_panel',
            options={'verbose_name_plural': 'InterviewPanels'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'question'},
        ),
        migrations.AlterModelOptions(
            name='question_status',
            options={'verbose_name_plural': 'Question_Staus'},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'verbose_name_plural': 'Rounds'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name_plural': 'Seasons'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='sectional_marks',
            options={'verbose_name_plural': 'Sectional_marks'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
