# Generated by Django 4.1.1 on 2022-09-11 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_candidate_options_alter_infotoconvey_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question_status',
            options={'verbose_name_plural': 'Question_Status'},
        ),
    ]
