# Generated by Django 4.1.1 on 2022-09-11 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_question_status_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round_info',
            name='panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainapp.interview_panel'),
        ),
    ]
