# Generated by Django 4.1.1 on 2022-09-11 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_round_info_panel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview_panel',
            options={'verbose_name_plural': 'Interview_Panels'},
        ),
    ]
