# Generated by Django 4.1.1 on 2022-11-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_infotoconvey_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='number_of_questions',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='round',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='type',
            field=models.CharField(choices=[('IT', ' Tech Interview'), ('IH', 'HR INTerview'), ('P', 'Project'), ('T', 'Test')], max_length=2),
        ),
    ]
