# Generated by Django 4.1.1 on 2022-09-12 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_interview_panel_custom_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='rounds',
            field=models.ManyToManyField(related_name='candidate_rounds', through='mainapp.Round_Info', to='mainapp.round'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_season', to='mainapp.season'),
        ),
        migrations.AlterField(
            model_name='infotoconvey',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to='mainapp.candidate'),
        ),
        migrations.AlterField(
            model_name='interview_panel',
            name='members',
            field=models.ManyToManyField(related_name='panel_members', to='mainapp.user'),
        ),
        migrations.AlterField(
            model_name='interview_panel',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_season', to='mainapp.season'),
        ),
        migrations.AlterField(
            model_name='question',
            name='asignee',
            field=models.ManyToManyField(related_name='question_asignees', to='mainapp.user'),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_section', to='mainapp.section'),
        ),
        migrations.AlterField(
            model_name='question_status',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_info', to='mainapp.question'),
        ),
        migrations.AlterField(
            model_name='question_status',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_student_info', to='mainapp.candidate'),
        ),
        migrations.AlterField(
            model_name='round',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_season', to='mainapp.season'),
        ),
        migrations.AlterField(
            model_name='round_info',
            name='panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='round_panel', to='mainapp.interview_panel'),
        ),
        migrations.AlterField(
            model_name='round_info',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_info', to='mainapp.round'),
        ),
        migrations.AlterField(
            model_name='round_info',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_student_info', to='mainapp.candidate'),
        ),
        migrations.AlterField(
            model_name='section',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_round', to='mainapp.round'),
        ),
        migrations.AlterField(
            model_name='sectional_marks',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_section', to='mainapp.section'),
        ),
        migrations.AlterField(
            model_name='sectional_marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectional_marks_student', to='mainapp.candidate'),
        ),
    ]
