# Generated by Django 4.1.1 on 2022-11-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_section_number_of_questions_alter_round_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_name',
            field=models.TextField(default='random'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question_status',
            name='submission_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
