# Generated by Django 4.1.1 on 2022-11-04 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_question_question_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='submission_link',
        ),
    ]
