# Generated by Django 4.1.1 on 2022-11-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_question_submission_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='round_info',
            name='submission_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
