# Generated by Django 4.1.1 on 2022-11-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_round_info_submission_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_status',
            name='submission_link',
        ),
    ]
