# Generated by Django 4.1.1 on 2022-11-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_question_status_submission_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_status',
            name='normalized_marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
