# Generated by Django 4.1.1 on 2022-11-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_question_status_normalized_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectional_marks',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
