# Generated by Django 4.1.1 on 2022-11-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_question_status_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round_info',
            old_name='marks_obtained',
            new_name='_marks_obtained',
        ),
    ]
