# Generated by Django 4.1.1 on 2022-11-25 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_rename_marks_obtained_round_info__marks_obtained'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round_info',
            options={'verbose_name': 'Round_Info', 'verbose_name_plural': 'Round_Info'},
        ),
    ]
