# Generated by Django 4.1.1 on 2022-11-28 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview_panel',
            name='current_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.candidate'),
        ),
    ]
