# Generated by Django 4.1.1 on 2022-12-03 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0020_interview_panel_current_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="infotoconvey",
            name="round_info",
            field=models.ForeignKey(
                blank=True,
                default=28,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.round_info",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="round_info",
            name="panel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="round_panel",
                to="mainapp.interview_panel",
            ),
        ),
    ]
