# Generated by Django 4.1.1 on 2023-02-17 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_sectional_marks_normalized_marks_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='round_info',
            unique_together={('student', 'round')},
        ),
    ]
