# Generated by Django 4.1.1 on 2023-02-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_alter_round_info_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectional_marks',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
