# Generated by Django 4.1.1 on 2023-03-10 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_round_info_normalized_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.interview_panel'),
        ),
    ]
