# Generated by Django 4.1.1 on 2023-03-11 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_infotoconvey_round_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.round')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.season')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_waitlist', to='mainapp.candidate')),
            ],
            options={
                'verbose_name_plural': 'Candidates',
            },
        ),
    ]
