# Generated by Django 4.1.1 on 2023-03-12 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_waitlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='rounds',
        ),
        migrations.RemoveField(
            model_name='question_status',
            name='is_checked',
        ),
        migrations.RemoveField(
            model_name='round',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='round',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='section',
            name='number_of_questions',
        ),
        migrations.AddField(
            model_name='interview_panel',
            name='current_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.round'),
        ),
        migrations.AddField(
            model_name='question',
            name='max_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
